version: '3.2'

volumes:
  static_volume:
  postgres_data:

services:

  cores:
    build:
      context: ./fancybin
    links:
      - postgres:postgres
    environment:
      # basic setup
      - HOSTNAME=fancybin # which hostname should django accept requests from (in addition to localhost)
      - SECRET_KEY=uhriagseruiguaeiorghozagraioehgr # make some entropy
      - DEBUG=False # turn on the *very* (dangerously) verbose error pages

      # database
      - POSTGRES_HOST=postgres # hostname of psql in docker stack
      - POSTGRES_PASSWORD=password # pick a password
      - POSTGRES_USER=django

      # version footer
      - CHANGELOGLINK=False
    depends_on:
      - postgres
    restart: always
    volumes:
      - static_volume:/srv/static
  
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=fancybin
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
    command: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/srv/static
    depends_on:
      - fancybin
    restart: always

