# Generated by Django 3.1.1 on 2020-09-30 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField(max_length=500)),
                ('style', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], default='info', max_length=30)),
                ('priority', models.IntegerField(choices=[(0, 'Very High'), (1, 'High'), (2, 'Normal'), (3, 'Low'), (4, 'Very Low')], default=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(blank=True, help_text='When should this message dissapear?', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Do you want this message to appear now?')),
                ('target', models.ForeignKey(blank=True, help_text='Show only to members of this group.', null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
